export const SIFTED_ITEM_TITLE_MAX_LENGTH = 500;
export const SIFTED_ITEM_LINK_MAX_LENGTH = 2048;
export const SIFTED_ITEM_SOURCE_MAX_LENGTH = 200;
export const SIFTED_ITEM_IMAGE_URL_MAX_LENGTH = 2048;
